# =========================================================
#  SIMON PHYSIO  GOLD MASTER RELEASE SCRIPT
#  VERSION : v1.0.0-premium
#  WARNING : DO NOT EDIT THIS FILE DIRECTLY
# =========================================================
Write-Host ""
Write-Host "=== SIMON PHYSIO GOLD MASTER ===" -ForegroundColor Cyan
Write-Host ("Repo      : " + (Resolve-Path .))
Write-Host ("Flutter   : " + (& where flutter 2>$null))
Write-Host ("Git       : " + (& where git 2>$null))
Write-Host ("Branch    : " + (git branch --show-current))
$dirty = git status --porcelain
Write-Host ("Dirty     : " + ($(if ($dirty) { 'YES' } else { 'NO' })))
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""
# =========================================================
# SIMON_AUTOPILOT_PREMIUM_V1.ps1
# Premium MVP v1 "Physio OS" â€” build + package + push (no manual)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Say($m) { Write-Host $m -ForegroundColor Cyan }
function Ok($m) { Write-Host $m -ForegroundColor Green }
function Warn($m) { Write-Host $m -ForegroundColor Yellow }
function Die($m) { Write-Host $m -ForegroundColor Red; throw $m }

$ROOT = (Resolve-Path ".").Path
if (!(Test-Path (Join-Path $ROOT ".git"))) { Die "Not in a git repo. Run from C:\SIMON\simon_physio" }

# --- Token check (push without prompts)
if ([string]::IsNullOrWhiteSpace(${env}:GITHUB_TOKEN)) {
    Die "Missing GITHUB_TOKEN env var. Set it: setx GITHUB_TOKEN `"ghp_...`" then reopen PowerShell."
}

# --- Flutter locate (PATH or Puro)
function Find-Flutter {
    $cmd = Get-Command flutter -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }

    $puro = Join-Path ${env}:USERPROFILE ".puro\envs\stable\flutter\bin\flutter.bat"
    if (Test-Path $puro) { return $puro }

    Die "Flutter not found. Install Flutter or Puro stable env."
}
$FLUTTER = Find-Flutter
Ok "Project: $ROOT"
Ok "Flutter:  $FLUTTER"

# --- Kill any running app to avoid locked DLLs
Say "==> Killing running simon_physio.exe (if any)..."
Get-Process simon_physio -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 250

# --- Ensure .gitignore covers junk
Say "==> Updating .gitignore (ignore build/dist/backups)..."
$gitignore = Join-Path $ROOT ".gitignore"
if (!(Test-Path $gitignore)) { "" | Out-File -Encoding utf8 $gitignore }
$append = @"
# Build / dist / local junk
DIST/
build/
.dart_tool/
windows/flutter/ephemeral/
TOOLS/_PREMIUM_OUT/
TOOLS/_BACKUPS/
# sanitised example
$existing = Get-Content $gitignore -ErrorAction SilentlyContinue | Out-String
if ($existing -notmatch "TOOLS/_BACKUPS/") {
  $append | Out-File -Encoding utf8 -Append $gitignore
}

# --- Switch branch
$BRANCH = "feature/premium-v1"
Say "==> Switching to branch: $BRANCH"
# --- SAFE: create branch if missing, else switch ---
$null = & git show-ref --verify --quiet ("refs/heads/{0}" -f $BRANCH)
$branchExists = ($LASTEXITCODE -eq 0)
if ($branchExists) {
  git checkout $BRANCH | Out-Null
} else {
  git checkout -b $BRANCH | Out-Null
}
# --------------------------------------------------
if ($LASTEXITCODE -ne 0) { git checkout -b $BRANCH | Out-Null }

# --- Directory layout
$PREM = Join-Path $ROOT "lib\premium"
New-Item -ItemType Directory -Force -Path $PREM | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $PREM "screens") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $PREM "widgets") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $PREM "models") | Out-Null

# --- Write Premium Physio OS (MVP v1)
Say "==> Writing Premium MVP v1 (Physio OS) files..."

@'
import 'package:flutter/material.dart';
import 'screens/dashboard_screen.dart';
import 'screens/clients_screen.dart';
import 'screens/calendar_screen.dart';
import 'screens/exercises_screen.dart';
import 'screens/programs_screen.dart';
import 'screens/intake_forms_screen.dart';
import 'screens/progress_screen.dart';
import 'screens/reports_screen.dart';
import 'screens/settings_screen.dart';

class PremiumPhysioOSApp extends StatelessWidget {
  const PremiumPhysioOSApp({super.key});

  @override
  Widget build(BuildContext context) {
    final colorScheme = ColorScheme.fromSeed(seedColor: const Color(0xFF00D4FF), brightness: Brightness.dark);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Simon Physio â€” Premium',
      theme: ThemeData(
        colorScheme: colorScheme,
        useMaterial3: true,
        scaffoldBackgroundColor: const Color(0xFF0B0F14),
        cardTheme: const CardThemeData(
          elevation: 0,
          margin: EdgeInsets.zero,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(18))),
        ),
      ),
      home: const PremiumShell(),
    );
  }
}

class PremiumShell extends StatefulWidget {
  const PremiumShell({super.key});

  @override
  State<PremiumShell> createState() => _PremiumShellState();
}

class _PremiumShellState extends State<PremiumShell> {
  int index = 0;

  final pages = const [
    DashboardScreen(),
    ClientsScreen(),
    CalendarScreen(),
    ExercisesScreen(),
    ProgramsScreen(),
    IntakeFormsScreen(),
    ProgressScreen(),
    ReportsScreen(),
    SettingsScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, c) {
        final wide = c.maxWidth >= 980;
        return Scaffold(
          body: Row(
            children: [
              if (wide) _SideRail(index: index, onTap: (i) => setState(() => index = i)),
              Expanded(child: pages[index]),
            ],
          ),
          bottomNavigationBar: wide ? null : _BottomNav(index: index, onTap: (i) => setState(() => index = i)),
        );
      },
    );
  }
}

class _BottomNav extends StatelessWidget {
  final int index;
  final ValueChanged<int> onTap;
  const _BottomNav({required this.index, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return NavigationBar(
      selectedIndex: index,
      onDestinationSelected: onTap,
      destinations: const [
        NavigationDestination(icon: Icon(Icons.dashboard_rounded), label: 'Dashboard'),
        NavigationDestination(icon: Icon(Icons.people_alt_rounded), label: 'Clients'),
        NavigationDestination(icon: Icon(Icons.calendar_month_rounded), label: 'Calendar'),
        NavigationDestination(icon: Icon(Icons.fitness_center_rounded), label: 'Exercises'),
        NavigationDestination(icon: Icon(Icons.playlist_add_check_rounded), label: 'Programs'),
      ],
    );
  }
}

class _SideRail extends StatelessWidget {
  final int index;
  final ValueChanged<int> onTap;
  const _SideRail({required this.index, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 280,
      decoration: const BoxDecoration(
        color: Color(0xFF0E141C),
        border: Border(right: BorderSide(color: Color(0xFF1A2330))),
      ),
      child: Column(
        children: [
          const SizedBox(height: 18),
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 16),
            child: _BrandHeader(),
          ),
          const SizedBox(height: 12),
          Expanded(
            child: ListView(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
              children: [
                _NavItem(icon: Icons.dashboard_rounded, label: "Dashboard", i: 0, index: index, onTap: onTap),
                _NavItem(icon: Icons.people_alt_rounded, label: "Clients", i: 1, index: index, onTap: onTap),
                _NavItem(icon: Icons.calendar_month_rounded, label: "Calendar", i: 2, index: index, onTap: onTap),
                _NavItem(icon: Icons.fitness_center_rounded, label: "Exercises", i: 3, index: index, onTap: onTap),
                _NavItem(icon: Icons.playlist_add_check_rounded, label: "Programs", i: 4, index: index, onTap: onTap),
                const Divider(height: 26),
                _NavItem(icon: Icons.assignment_rounded, label: "Intake Forms", i: 5, index: index, onTap: onTap),
                _NavItem(icon: Icons.show_chart_rounded, label: "Progress", i: 6, index: index, onTap: onTap),
                _NavItem(icon: Icons.summarize_rounded, label: "Reports", i: 7, index: index, onTap: onTap),
                const Divider(height: 26),
                _NavItem(icon: Icons.settings_rounded, label: "Settings", i: 8, index: index, onTap: onTap),
              ],
            ),
          ),
          const Padding(
            padding: EdgeInsets.all(14),
            child: _FooterHint(),
          ),
        ],
      ),
    );
  }
}

class _BrandHeader extends StatelessWidget {
  const _BrandHeader();
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(18),
        gradient: const LinearGradient(colors: [Color(0xFF00D4FF), Color(0xFF7C4DFF)]),
      ),
      child: const Row(
        children: [
          Icon(Icons.health_and_safety_rounded, color: Colors.black, size: 28),
          SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text("Simon Physio", style: TextStyle(color: Colors.black, fontWeight: FontWeight.w900, fontSize: 16)),
                Text("Premium â€” Physio OS v1", style: TextStyle(color: Colors.black87, fontWeight: FontWeight.w600)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _NavItem extends StatelessWidget {
  final IconData icon;
  final String label;
  final int i;
  final int index;
  final ValueChanged<int> onTap;

  const _NavItem({required this.icon, required this.label, required this.i, required this.index, required this.onTap});

  @override
  Widget build(BuildContext context) {
    final selected = i == index;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: InkWell(
        borderRadius: BorderRadius.circular(14),
        onTap: () => onTap(i),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            color: selected ? const Color(0xFF121D2A) : Colors.transparent,
            border: Border.all(color: selected ? const Color(0xFF2B3B52) : const Color(0x00000000)),
          ),
          child: Row(
            children: [
              Icon(icon, color: selected ? const Color(0xFF00D4FF) : const Color(0xFF9FB0C6)),
              const SizedBox(width: 10),
              Expanded(
                child: Text(label,
                    style: TextStyle(
                      color: selected ? Colors.white : const Color(0xFFC6D3E6),
                      fontWeight: selected ? FontWeight.w800 : FontWeight.w600,
                    )),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _FooterHint extends StatelessWidget {
  const _FooterHint();
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: const Color(0xFF1A2330)),
        color: const Color(0xFF0B0F14),
      ),
      child: const Text(
        "MVP v1 focus:\nâ€¢ Client CRM\nâ€¢ Sessions + notes\nâ€¢ Home programs\nâ€¢ Intake forms\nâ€¢ Progress + reports\n\nNext: billing/NDIS, templates, cloud sync, AI assist.",
        style: TextStyle(color: Color(0xFF9FB0C6), height: 1.25),
      ),
    );
  }
}
'@ | Out-File -Encoding utf8 (Join-Path $PREM "premium_physio_os_app.dart")

# --- Screens (functional MVP placeholders with â€œrealâ€ structure)
$screenMap = @{
  "dashboard_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class DashboardScreen extends StatelessWidget {
  const DashboardScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Dashboard",
      subtitle: "Todayâ€™s workload, key clients, and quick actions.",
      children: const [
        _Grid(),
      ],
    );
  }
}

class _Grid extends StatelessWidget {
  const _Grid();
  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: 14,
      runSpacing: 14,
      children: const [
        _KpiCard(title: "Appointments", value: "â€”", hint: "Today"),
        _KpiCard(title: "Clients", value: "â€”", hint: "Active"),
        _KpiCard(title: "Programs", value: "â€”", hint: "Assigned"),
        _KpiCard(title: "Tasks", value: "â€”", hint: "Outstanding"),
      ],
    );
  }
}

class _KpiCard extends StatelessWidget {
  final String title;
  final String value;
  final String hint;
  const _KpiCard({required this.title, required this.value, required this.hint});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 280,
      child: Card(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(title, style: const TextStyle(color: Color(0xFF9FB0C6), fontWeight: FontWeight.w700)),
              const SizedBox(height: 10),
              Text(value, style: const TextStyle(fontSize: 32, fontWeight: FontWeight.w900)),
              const SizedBox(height: 6),
              Text(hint, style: const TextStyle(color: Color(0xFF9FB0C6))),
            ],
          ),
        ),
      ),
    );
  }
}
'@;

  "clients_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class ClientsScreen extends StatelessWidget {
  const ClientsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Clients",
      subtitle: "CRM, injuries, goals, notes, and programs.",
      actions: [
        FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.person_add_alt_1_rounded), label: const Text("New Client")),
      ],
      children: [
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    decoration: InputDecoration(
                      hintText: "Search clients (name, injury, phone, email)â€¦",
                      prefixIcon: const Icon(Icons.search_rounded),
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                OutlinedButton.icon(onPressed: () {}, icon: const Icon(Icons.filter_alt_rounded), label: const Text("Filter")),
              ],
            ),
          ),
        ),
        const SizedBox(height: 14),
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Text(
              "MVP v1: client list + client profile + session notes + assigned home programs.\n"
              "Next: intake import, consent, attachments, messaging, templates.",
              style: const TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "calendar_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class CalendarScreen extends StatelessWidget {
  const CalendarScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Calendar",
      subtitle: "Appointments, reminders, follow-ups.",
      actions: [
        FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.add_rounded), label: const Text("New Appointment")),
      ],
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: local appointments + reminders.\nNext: Google Calendar sync + SMS/email reminders.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "exercises_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class ExercisesScreen extends StatelessWidget {
  const ExercisesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Exercise Library",
      subtitle: "Templates, progressions, cues, contraindications.",
      actions: [
        FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.add_rounded), label: const Text("New Exercise")),
      ],
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: exercise catalog + tags + notes.\nNext: video attachments, printable sheets, client-facing export.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "programs_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class ProgramsScreen extends StatelessWidget {
  const ProgramsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Home Programs",
      subtitle: "Build, assign, and track adherence.",
      actions: [
        FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.playlist_add_rounded), label: const Text("New Program")),
      ],
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: program builder + assign to client.\nNext: patient portal, adherence check-ins, push reminders.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "intake_forms_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class IntakeFormsScreen extends StatelessWidget {
  const IntakeFormsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Intake Forms",
      subtitle: "Assessments, consent, questionnaires.",
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: standard intake templates (pain scale, history, red flags).\nNext: shareable link + signature + PDF export.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "progress_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class ProgressScreen extends StatelessWidget {
  const ProgressScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Progress",
      subtitle: "Pain scores, ROM, strength, milestones.",
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: basic progress entries.\nNext: graphs per metric + adherence correlation + automated summaries.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "reports_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class ReportsScreen extends StatelessWidget {
  const ReportsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Reports",
      subtitle: "Export-ready clinical notes and summaries.",
      actions: [
        FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.picture_as_pdf_rounded), label: const Text("Export PDF")),
      ],
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: report templates.\nNext: NDIS-ready reports + GP letters + outcome measures pack.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;

  "settings_screen.dart" = @'
import 'package:flutter/material.dart';
import '../widgets/premium_shell_scaffold.dart';

class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PremiumShellScaffold(
      title: "Settings",
      subtitle: "Clinic profile, templates, backups.",
      children: const [
        Card(
          child: Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              "MVP v1: local settings.\nNext: encrypted backups + cloud sync + multi-clinic profiles.",
              style: TextStyle(color: Color(0xFF9FB0C6), height: 1.3),
            ),
          ),
        ),
      ],
    );
  }
}
'@;
}

$screenDir = Join-Path $PREM "screens"
foreach ($k in $screenMap.Keys) {
  $screenMap[$k] | Out-File -Encoding utf8 (Join-Path $screenDir $k)
}

# --- Shared scaffold widget
@'
import 'package:flutter/material.dart';

class PremiumShellScaffold extends StatelessWidget {
  final String title;
  final String subtitle;
  final List<Widget> children;
  final List<Widget> actions;

  const PremiumShellScaffold({
    super.key,
    required this.title,
    required this.subtitle,
    required this.children,
    this.actions = const [],
  });

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(18),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(title, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w900)),
                      const SizedBox(height: 4),
                      Text(subtitle, style: const TextStyle(color: Color(0xFF9FB0C6))),
                    ],
                  ),
                ),
                const SizedBox(width: 12),
                ...actions,
              ],
            ),
            const SizedBox(height: 14),
            Expanded(
              child: ListView(
                children: children,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
'@ | Out-File -Encoding utf8 (Join-Path $PREM "widgets\premium_shell_scaffold.dart")

# --- Patch lib/main.dart to run PremiumPhysioOSApp (forced)
Say "==> Forcing lib/main.dart to PremiumPhysioOSApp..."
$mainPath = Join-Path $ROOT "lib\main.dart"
$backupDir = Join-Path $ROOT "TOOLS\_BACKUPS"
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
Copy-Item $mainPath (Join-Path $backupDir ("main.dart.$stamp.bak")) -Force

@'
import 'package:flutter/widgets.dart';
import 'premium/premium_physio_os_app.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const PremiumPhysioOSApp());
}
'@ | Out-File -Encoding utf8 $mainPath

# --- Flutter build pipeline
Say "==> flutter config --enable-windows-desktop"
& $FLUTTER config --enable-windows-desktop | Out-Null

Say "==> flutter clean"
& $FLUTTER clean | Out-Null

Say "==> flutter pub get"
& $FLUTTER pub get | Out-Null

Say "==> flutter analyze"
& $FLUTTER analyze | Out-Null
Say "==> (skipped) flutter test (Windows release build)"
Say "==> flutter build windows --release"
& $FLUTTER build windows --release | Out-Null


if ($LASTEXITCODE -ne 0) { Die "Build failed (flutter build windows). Stopping before packaging." }
# --- Packaging portable (robocopy mirror avoids locked file drama)
$DIST = Join-Path $ROOT "DIST"
$src  = Join-Path $ROOT "build\windows\x64\runner\Release"
$dest = Join-Path $DIST "windows_release_portable"
$zip  = Join-Path $DIST "simon_physio_windows_release_portable.zip"
$exeOut = Join-Path $DIST "simon_physio_premium.exe"

New-Item -ItemType Directory -Force -Path $DIST | Out-Null
if (Test-Path $dest) { Remove-Item $dest -Recurse -Force -ErrorAction SilentlyContinue | Out-Null }
New-Item -ItemType Directory -Force -Path $dest | Out-Null

Say "==> Packaging portable (robocopy mirror)..."
$rc = robocopy $src $dest /MIR /R:3 /W:1 /NFL /NDL /NP /NJH /NJS
# robocopy returns weird codes; treat >=8 as failure
if ($LASTEXITCODE -ge 8) { Die "Robocopy failed with code $LASTEXITCODE" }

Copy-Item (Join-Path $src "simon_physio.exe") $exeOut -Force
Ok "Portable folder ready: $dest"
Ok "EXE copied: $exeOut"

if (Test-Path $zip) { Remove-Item $zip -Force -ErrorAction SilentlyContinue | Out-Null }
Say "==> Zipping: $zip"
Compress-Archive -Path (Join-Path $dest "*") -DestinationPath $zip -Force
Ok "ZIP created: $zip"

# --- Git add/commit
Say "==> Git add/commit..."
git add .gitignore | Out-Null
git add lib\main.dart | Out-Null
git add lib\premium | Out-Null
# commit only if changes exist
$dirty = git status --porcelain
if ([string]::IsNullOrWhiteSpace($dirty)) {
  Warn "No code changes to commit."
} else {
  git commit -m "Premium MVP v1: Physio OS shell (clients/calendar/exercises/programs/intake/progress/reports)" | Out-Null
  Ok "Committed."
}

# --- Push using GIT_ASKPASS (no interactive prompts)
Say "==> Pushing to origin/$BRANCH (non-interactive)..."
$askpass = Join-Path ${env}:TEMP "git_askpass_token.cmd"
# sanitised example
@echo off
echo %GITHUB_TOKEN%
"@ | Out-File -Encoding ascii $askpass

${env}:GIT_ASKPASS = $askpass
${env}:GIT_TERMINAL_PROMPT = "0"

git push -u origin $BRANCH | Out-Null
Remove-Item $askpass -Force -ErrorAction SilentlyContinue | Out-Null

Ok "==============================="
Ok "DONE âœ… Premium MVP v1 built + packaged + pushed"
Ok "BRANCH  : $BRANCH"
Ok "PORTABLE: $dest"
Ok "ZIP     : $zip"
Ok "EXE     : $exeOut"
Ok "==============================="















